### ISSUE TITLE
Update doesn't work

### ISSUE THREAD

**Issue by jeffneedle** [obrevenge/obrevenge-iso#1]
Just installed 64-bit obrevenge.  Installed fine, but when I tried to update the system, I get an error that tells me there are file conflicts.  What is the fix?  Thanks.

**Comment by obrevenge** [comment]
The file conflict is from the ttf-dejavu package. Every Arch system had this issue. The fix is to force the update.
sudo pacman -S ttf-dejavu --force 

See this link:
https://www.archlinux.org/news/ttf-dejavu-237-will-require-forced-upgrade/

**Comment by jeffneedle** [comment]
Thanks!
