### ISSUE TITLE
XFCE4 panel question

### ISSUE THREAD

**Issue by jeffneedle** [obrevenge/obrevenge-iso#2]
Most XFCE4 based distros let you modify the keyboard definitions so that you can assign, say, the Windows key to invoke the Whisker Menu.  I can't find any place in obrevenge where this is made possible.  Can someone help?  Thanks.

**Comment by obrevenge** [comment]
There is a key bind tool the control panel that will allow you to set keybindings for different actions. Because it is based on openbox it works a little differently.

**Comment by obrevenge** [comment]
Keybindings can also be set manually in your ~/. config/openbox/rc.xml file. The command you want to use to open the whisker menu is xfce4-popup-whiskermenu

**Comment by jeffneedle** [comment]
Thanks again!
