### ISSUE TITLE
Fixes for touchpad (universal) - glx_nvidia support and COMPTON transparency fix

### ISSUE THREAD

**Issue by obsidianarch** [obrevenge/obrevenge-iso#3]
sudo nano /etc/X11/xorg.conf.d/synaptics.conf

add to that file:

Section "InputClass"
        Identifier      "Touchpad"                      # required
        MatchIsTouchpad "yes"                           # required
        Driver          "synaptics"                     # required
        Option          "MinSpeed"              "0.5"
        Option          "MaxSpeed"              "1.0"
        Option          "AccelFactor"           "0.075"
        Option          "TapButton1"            "1"
        Option          "TapButton2"            "2"     # multitouch
        Option          "TapButton3"            "3"     # multitouch
        Option          "VertTwoFingerScroll"   "1"     # multitouch
        Option          "HorizTwoFingerScroll"  "1"     # multitouch
        Option          "VertEdgeScroll"        "1"
        Option          "CoastingSpeed"         "8"
        Option          "CornerCoasting"        "1"
        Option          "CircularScrolling"     "1"
        Option          "CircScrollTrigger"     "7"
        Option          "EdgeMotionUseAlways"   "1"
        Option          "LBCornerButton"        "8"     # browser "back" btn
        Option          "RBCornerButton"        "9"     # browser "forward" btn
EndSection

will setup synaptics touch to click in X11 --- all windowmanagers ---
openbox, jwm, etc

For glx and nvidia support/errors
yaourt -S compton-garnetius-git

these fixes work for OBREVENGE

Ben Henderson, El Paso Texas :-)

**Comment by obrevenge** [comment]
Awesome! Thank you, sir!
