### ISSUE TITLE
esp flag won't set in manual partitioning

### ISSUE THREAD

**Issue by LinuxLowell** [obrevenge/obrevenge-iso#4]
Problem
=========
While using calamares installer, I need to manually configure the HD. I already had a /boot/efi partion created from a previous distro.  When I edit the partition and set it as /boot/efi and set the flag to 'esp', the flag setting is not retained.  As soon as I hit ok, the flag is discarded.

Steps to reproduce
=================
1) Have an existing Linux installation with a /boot/efi parition
2) Boot OBR ISO and start calamares
3) When paritioning HD, select "manual configuration"
4) Edit partitions per your configuration, edit /boot/efi partition with esp flag
5) Hit 'Next'
6) Popup window will appear stating you have a /boot/efi partition but the esp flag has not been set
7) Edit /boot/efi parition, you will note esp flag is not set
Note: At step 5, you can also edit the /boot/efi partition and see the flag has not been set

Workaround
===========
Replace step 4 of the with:
4a) Delete /boot/efi partition
4b) Select empty space left by deleted partition,select create
4c) Mount point /boot/efi, file system FAT32, flag esp
All will work fine

Perhaps this is a calamares defect. Never used calamares before, typicaly install Arch and OB from scratch but thought I would give this a try.  I encountered this problem using the 64 bit April 2017 OBR image that I dd'd (is that a verb?) to a USB flash device.

**Comment by LinuxLowell** [comment]
Just realized I probably put this issue in the wrong queue.  Does this belong in the revenge installer queue? I'm not sure what the difference between calamares and the revenge installer is.

**Comment by obrevenge** [comment]
Sorry for the delay in addressing this. This really needs to be submitted to the application team, but thanks for making me aware of it. I will check to see if this issue has been reported to them.
