### ISSUE TITLE
Password Dialog Box

### ISSUE THREAD

**Issue by swoopa** [obrevenge/obrevenge-iso#6]
RevengeOS with Gnome Desktop running Wayland, no reponse when clicking mouse or entering text from keyboard in password entry box when using Revenge-Tools or Revenge Welcome Screen.
![password-dialog-box](https://user-images.githubusercontent.com/25865515/28750216-8fbcb408-7516-11e7-85c3-22428545a11c.png)
![password-dialog-box-2](https://user-images.githubusercontent.com/25865515/28750217-96611588-7516-11e7-99c9-a131226e31bb.png)

**Comment by obrevenge** [comment]
This was due to an error in the Nemesis Installer. I just committed a fix which will now allow both Wayland and Xorg sessions in Gnome.

**Comment by obrevenge** [comment]
To fix in a installed system, try reinstalling the Gnome package group.

**Comment by obrevenge** [comment]
An additional fix was implemented to make x the default. The issue should he resolved.
