### ISSUE TITLE
Cancellation Nemesis Installer

### ISSUE THREAD

**Issue by swoopa** [obrevenge/obrevenge-iso#7]
When clicking cancel during install it continues the installation, this is critical especially at the final stages of install when confirming all details, if you decide you have incorrectly chosen the wrong install target and you cancel, it will continue to format the chosen drive as normal.

**Comment by spookykidmm** [comment]
Stopping the installation in the middle of formatting or any other step could be super damaging to the drive. that's why in the dialog, the --no-cancel option is passed

_Sent from my Samsung SAMSUNG-SM-G935A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by swoopa** [comment]
If I hit the Cancel button in this picture Install will continue.
![revengeos-cancellation](https://user-images.githubusercontent.com/25865515/29000461-fa5f78d6-7a9d-11e7-97fc-b14045c9d8c0.png)
If I select Cancel (Radio Button) in the next pic and select OK button this will actually cancel the installation
![revengeos-cancellation-2](https://user-images.githubusercontent.com/25865515/29000470-7e9bb6a0-7a9e-11e7-9afe-4898c5e41254.png)
It will then bring you back to this box selecting Cancel again.
![revengeos-cancellation-4](https://user-images.githubusercontent.com/25865515/29000482-d3f01b8c-7a9e-11e7-8d53-f0b8fc74dba4.png)
The last box allows you to close the installer or restart
![revengeos-cancellation-5](https://user-images.githubusercontent.com/25865515/29000495-313787a8-7a9f-11e7-9e0d-d63dc4cac0ee.png)
There is a right and wrong way to cancel, although the default behaviour in a lot of installers is to select the main cancel button, the Nemesis installer varies slightly from the normal, I believe in the case of any individual wanting to cancel the installation with doubts of the install target they would probably go for the main Cancel button as it's more outstanding.
I hope I'm not being too annoying with too much info, I just don't like to leave any stone unturned.
Kind Regards
Colin

**Comment by obrevenge** [comment]
I just pushed a fix for this that clarifies the dialog to confirm or exit. It is now presented with a simple question dialog with only the main "yes" or "no" responses, and no radio choices. I will leave the issue open for a few days to make sure that everything works well, and if there are no problems I will then close it. Thanks.
-Jody
