### ISSUE TITLE
/etc/locale.gen contains only installed language

### ISSUE THREAD

**Issue by ThanosApostolou** [obrevenge/obrevenge-iso#8]
I don't know if this is caused by the installation script or something else, but the **/etc/locale.gen** contains only the installed language after installation. This makes it hard to use more languages by just uncommenting the rest options like described in arch wiki.

It would be nice, if after the installation, the installed language was just uncommented in the file **/etc/locale.gen** and keep the rest commented language options.

**Comment by obrevenge** [comment]
I just pushed an update to the installer that will do as you requested, it will now leave the rest of the locales in the /etc/locale.gen commented out so that they can easily be selected later. Thanks for reporting the issue, you made a good point. I'm closing the issue now.

-Jody
